trigger: none

pool: Default  

variables:
  resourceGroupName: 'viewstudenttestrg'
  resourceGroupLocation: 'Australia East'
  accountNameValidate: 'view-student-db-validate'
  accountNameDevelopment: 'view-student-db-development'
  accountNameStaging: 'view-student-db-staging'
  accountNameProduction: 'view-student-db-production'
  containerThroughputValidate: 400
  containerThroughputDevelopment: 400
  containerThroughputStaging: 400
  containerThroughputProduction: 1000
  dbName: 'ViewStudentDb'
  azureResourceManagerConnection: 'Azure subscription 1(39e82e92-e9af-4a28-95dc-268d47637e28)'
  subscriptionId: '39e82e92-e9af-4a28-95dc-268d47637e28'
  azureSubscription: 'Azure subscription 1(39e82e92-e9af-4a28-95dc-268d47637e28)'

stages:
- stage: Lint
  jobs:
  - job: LintCode
    displayName: Lint code
    steps:
      - script: |
          az bicep upgrade
          az bicep restore --force
          az bicep build --file deploy/view-student-db/main.bicep
        name: LintBicepCode
        displayName: Run Bicep linter

- stage: Validation
  jobs:
  - job: ValidateBicepCode
    displayName: Validate Bicep code
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        name: RunPreflightValidation
        displayName: Run preflight validation
        inputs:
          azureResourceManagerConnection: $(azureResourceManagerConnection)
          subscriptionId: $(subscriptionId)
          location: $(resourceGroupLocation)
          deploymentMode: Validation
          resourceGroupName: $(resourceGroupName)
          csmFile: deploy/view-student-db/main.bicep
          overrideParameters: '-accountName "$(accountNameValidate)" -location "$(resourceGroupLocation)" -databaseName "$(dbName)" -throughput $(containerThroughputValidate)'

- stage: Deployment_Development 
  displayName: Development
  dependsOn: Validation
  condition: succeeded('Validation')
  jobs:
    - deployment: Development
      displayName: Development      
      pool: Default
      environment: 'ViewStudent DB Development'
      strategy:
        runOnce:
          deploy:
            steps:              
              - task: AzureResourceManagerTemplateDeployment@3
                name: DeployBicepFile
                displayName: Deploy Bicep file
                inputs:
                  azureResourceManagerConnection: $(azureResourceManagerConnection)
                  subscriptionId: $(subscriptionId)
                  deploymentName: $(Build.BuildNumber)
                  location: $(resourceGroupLocation)
                  resourceGroupName: $(resourceGroupName)
                  csmFile: deploy/view-student-db/main.bicep
                  overrideParameters: '-accountName "$(accountNameDevelopment)" -location "$(resourceGroupLocation)" -databaseName "$(dbName)" -throughput $(containerThroughputDevelopment)'

- stage: Deployment_Staging 
  displayName: Staging
  dependsOn: Deployment_Development
  condition: succeeded('Deployment_Development')
  jobs:
    - deployment: Staging
      displayName: Staging      
      pool: Default
      environment: 'ViewStudent DB Staging'
      strategy:
        runOnce:
          deploy:
            steps:              
              - task: AzureResourceManagerTemplateDeployment@3
                name: DeployBicepFile
                displayName: Deploy Bicep file
                inputs:
                  azureResourceManagerConnection: $(azureResourceManagerConnection)
                  subscriptionId: $(subscriptionId)
                  deploymentName: $(Build.BuildNumber)
                  location: $(resourceGroupLocation)
                  resourceGroupName: $(resourceGroupName)
                  csmFile: deploy/view-student-db/main.bicep
                  overrideParameters: '-accountName "$(accountNameStaging)" -location "$(resourceGroupLocation)" -databaseName "$(dbName)" -throughput $(containerThroughputStaging)'

- stage: Deployment_Production
  displayName: Production
  dependsOn: Deployment_Staging
  condition: succeeded('Deployment_Staging')
  jobs:
    - deployment: Production
      displayName: Production
      pool: Default
      environment: 'ViewStudent DB Production'
      strategy:
        runOnce:
          deploy:
            steps:              
              - task: AzureResourceManagerTemplateDeployment@3
                name: DeployBicepFile
                displayName: Deploy Bicep file
                inputs:
                  azureResourceManagerConnection: $(azureResourceManagerConnection)
                  subscriptionId: $(subscriptionId)
                  deploymentName: $(Build.BuildNumber)
                  location: $(resourceGroupLocation)
                  resourceGroupName: $(resourceGroupName)
                  csmFile: deploy/view-student-db/main.bicep
                  overrideParameters: '-accountName "$(accountNameProduction)" -location "$(resourceGroupLocation)" -databaseName "$(dbName)" -throughput $(containerThroughputProduction)'
